//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ciroque.Foundations.FeatureStore.Instrumentation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PerformanceCounterNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PerformanceCounterNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ciroque.Foundations.FeatureStore.Instrumentation.PerformanceCounterNameResources", typeof(PerformanceCounterNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckFeatureState call  count..
        /// </summary>
        internal static string CHECK_FEATURE_STATE_CALL_COUNT {
            get {
                return ResourceManager.GetString("CHECK_FEATURE_STATE_CALL_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times the CheckFeatureState method has been called since the service started..
        /// </summary>
        internal static string CHECK_FEATURE_STATE_CALL_COUNT_HELP {
            get {
                return ResourceManager.GetString("CHECK_FEATURE_STATE_CALL_COUNT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckFeatureState execution time..
        /// </summary>
        internal static string CHECK_FEATURE_STATE_EXECUTION_TIME {
            get {
                return ResourceManager.GetString("CHECK_FEATURE_STATE_EXECUTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of time, in milliseconds, that the CheckFeatureState method takes to complete..
        /// </summary>
        internal static string CHECK_FEATURE_STATE_EXECUTION_TIME_HELP {
            get {
                return ResourceManager.GetString("CHECK_FEATURE_STATE_EXECUTION_TIME_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateFeature call count..
        /// </summary>
        internal static string CREATE_FEATURE_CALL_COUNT {
            get {
                return ResourceManager.GetString("CREATE_FEATURE_CALL_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times the CreateFeature method has been called since the service started..
        /// </summary>
        internal static string CREATE_FEATURE_CALL_COUNT_HELP {
            get {
                return ResourceManager.GetString("CREATE_FEATURE_CALL_COUNT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateFeature execution time..
        /// </summary>
        internal static string CREATE_FEATURE_EXECUTION_TIME {
            get {
                return ResourceManager.GetString("CREATE_FEATURE_EXECUTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of time, in milliseconds, that the CreateFeature method takes to complete..
        /// </summary>
        internal static string CREATE_FEATURE_EXECUTION_TIME_HELP {
            get {
                return ResourceManager.GetString("CREATE_FEATURE_EXECUTION_TIME_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains Performance Counters related to the Microsoft Advertising FeatureStore Service..
        /// </summary>
        internal static string PERFORMANCE_COUNTER_CATEGORY_HELP {
            get {
                return ResourceManager.GetString("PERFORMANCE_COUNTER_CATEGORY_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Advertising Feature Store.
        /// </summary>
        internal static string PERFORMANCE_COUNTER_CATEGORY_NAME {
            get {
                return ResourceManager.GetString("PERFORMANCE_COUNTER_CATEGORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetrieveDefinedFeatures call count..
        /// </summary>
        internal static string RETRIEVE_DEFINED_FEATURES_COUNT {
            get {
                return ResourceManager.GetString("RETRIEVE_DEFINED_FEATURES_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times the RetrieveDefinedFeatures method has been called since the service started..
        /// </summary>
        internal static string RETRIEVE_DEFINED_FEATURES_COUNT_HELP {
            get {
                return ResourceManager.GetString("RETRIEVE_DEFINED_FEATURES_COUNT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetrieveDefinedFeatures execution time..
        /// </summary>
        internal static string RETRIEVE_DEFINED_FEATURES_EXECUTION_TIME {
            get {
                return ResourceManager.GetString("RETRIEVE_DEFINED_FEATURES_EXECUTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of time, in milliseconds, that the RetrieveDefinedFeatures method takes to complete..
        /// </summary>
        internal static string RETRIEVE_DEFINED_FEATURES_EXECUTION_TIME_HELP {
            get {
                return ResourceManager.GetString("RETRIEVE_DEFINED_FEATURES_EXECUTION_TIME_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateFeatureState call count..
        /// </summary>
        internal static string UPDATE_FEATURE_STATE_COUNT {
            get {
                return ResourceManager.GetString("UPDATE_FEATURE_STATE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of times the UpdateFeatureState method has been called since the service started..
        /// </summary>
        internal static string UPDATE_FEATURE_STATE_COUNT_HELP {
            get {
                return ResourceManager.GetString("UPDATE_FEATURE_STATE_COUNT_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateFeatureState execution time..
        /// </summary>
        internal static string UPDATE_FEATURE_STATE_EXECUTION_TIME {
            get {
                return ResourceManager.GetString("UPDATE_FEATURE_STATE_EXECUTION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of time, in milliseconds, that the UpdateFeatureState method takes to complete..
        /// </summary>
        internal static string UPDATE_FEATURE_STATE_EXECUTION_TIME_HELP {
            get {
                return ResourceManager.GetString("UPDATE_FEATURE_STATE_EXECUTION_TIME_HELP", resourceCulture);
            }
        }
    }
}
