//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureStoreServiceSmokeTester.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlTextsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlTextsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatureStoreServiceSmokeTester.Resources.ControlTextsResource", typeof(ControlTextsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureIdTextbox.
        /// </summary>
        internal static string CONTROL_NAME_FEATURE_ID_TEXTBOX {
            get {
                return ResourceManager.GetString("CONTROL_NAME_FEATURE_ID_TEXTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureNameTextbox.
        /// </summary>
        internal static string CONTROL_NAME_FEATURE_NAME_TEXTBOX {
            get {
                return ResourceManager.GetString("CONTROL_NAME_FEATURE_NAME_TEXTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureOwnerIdTextbox.
        /// </summary>
        internal static string CONTROL_NAME_FEATURE_OWNER_ID_TEXTBOX {
            get {
                return ResourceManager.GetString("CONTROL_NAME_FEATURE_OWNER_ID_TEXTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureSpaceTextbox.
        /// </summary>
        internal static string CONTROL_NAME_FEATURE_SPACE_TEXTBOX {
            get {
                return ResourceManager.GetString("CONTROL_NAME_FEATURE_SPACE_TEXTBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureStateCheckBox.
        /// </summary>
        internal static string CONTROL_NAME_FEATURE_STATE_CHECKBOX {
            get {
                return ResourceManager.GetString("CONTROL_NAME_FEATURE_STATE_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureStateMethodArgsPanel.
        /// </summary>
        internal static string CONTROL_NAME_FEATURE_STATE_METHOD_ARGS_PANEL {
            get {
                return ResourceManager.GetString("CONTROL_NAME_FEATURE_STATE_METHOD_ARGS_PANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateNewGuidForOwnerId.
        /// </summary>
        internal static string CONTROL_NAME_NEW_OWNERID_GUID_BUTTON_NAME {
            get {
                return ResourceManager.GetString("CONTROL_NAME_NEW_OWNERID_GUID_BUTTON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HELP_TAB_PAGE_TEXT {
            get {
                return ResourceManager.GetString("HELP_TAB_PAGE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Id.
        /// </summary>
        internal static string LABEL_TEXT_ID {
            get {
                return ResourceManager.GetString("LABEL_TEXT_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LABEL_TEXT_NAME {
            get {
                return ResourceManager.GetString("LABEL_TEXT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Id.
        /// </summary>
        internal static string LABEL_TEXT_OWNER_ID {
            get {
                return ResourceManager.GetString("LABEL_TEXT_OWNER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string LABEL_TEXT_SPACE {
            get {
                return ResourceManager.GetString("LABEL_TEXT_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string LABEL_TEXT_STATE {
            get {
                return ResourceManager.GetString("LABEL_TEXT_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Feature State.
        /// </summary>
        internal static string TAB_PAGE_TEXT_CHECK_FEATURE_STATE {
            get {
                return ResourceManager.GetString("TAB_PAGE_TEXT_CHECK_FEATURE_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Feature.
        /// </summary>
        internal static string TAB_PAGE_TEXT_CREATE_FEATURE {
            get {
                return ResourceManager.GetString("TAB_PAGE_TEXT_CREATE_FEATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Defined Features.
        /// </summary>
        internal static string TAB_PAGE_TEXT_RETRIEVE_DEFINED_FEATURES {
            get {
                return ResourceManager.GetString("TAB_PAGE_TEXT_RETRIEVE_DEFINED_FEATURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Feature State.
        /// </summary>
        internal static string TAB_PAGE_TEXT_UPDATE_FEATURE_STATE {
            get {
                return ResourceManager.GetString("TAB_PAGE_TEXT_UPDATE_FEATURE_STATE", resourceCulture);
            }
        }
    }
}
