//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureStoreServiceSmokeTester.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RtfResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RtfResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatureStoreServiceSmokeTester.Resources.RtfResources", typeof(RtfResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \viewkind4\uc1\pard\sa200\sl276\slmult1\cf6\lang9\b\f0\fs32 {0}.
        /// </summary>
        internal static string EXCEPTION_MESSAGE_FORMAT {
            get {
                return ResourceManager.GetString("EXCEPTION_MESSAGE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \fs22\tab\cf4 Feature\par
        ///\cf0\b0\tab\tab Feature Id: \cf5\b {0}\cf0\b0\par
        ///\cf0\b0\tab\tab Owner Id: \cf5\b {1}\cf0\b0\par
        ///\cf0\b0\tab\tab Space: \cf5\b {2}\cf3\par
        ///\cf0\b0\tab\tab Name: \cf5\b {3}\cf3\par
        ///\cf0\b0\tab\tab Enabled: \cf5\b {4}\cf3\par.
        /// </summary>
        internal static string FEATURE_FORMAT {
            get {
                return ResourceManager.GetString("FEATURE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \fs22\tab\cf4 Key\par
        ///\cf0\b0\tab\tab Feature Id: \cf5\b {0}\cf0\b0\par
        ///\tab\tab Owner Id: \cf5\b {1}\cf0\b0\par
        ///\tab\tab Space: \cf5\b {2}\cf3\par.
        /// </summary>
        internal static string FEATURE_KEY_FORMAT {
            get {
                return ResourceManager.GetString("FEATURE_KEY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \fs22\tab\cf4 Key\par
        ///\tab\tab Owner Id: \cf5\b {0}\cf0\b0\par
        ///\tab\tab Space: \cf5\b {1}\cf3\par.
        /// </summary>
        internal static string FEATURE_SCOPE_FORMAT {
            get {
                return ResourceManager.GetString("FEATURE_SCOPE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \par
        ///---------- Inner Exception ----------\par
        ///\par.
        /// </summary>
        internal static string INNER_EXCEPTION_DELIMETER {
            get {
                return ResourceManager.GetString("INNER_EXCEPTION_DELIMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \fs22\tab\cf4 Header\par
        ///\cf0\b0\tab\tab MessageId: \cf5\b {0}\par
        ///\cf0\b0\tab\tab Origination IP Address: \cf5\b {1}\cf0\b0\par
        ///\tab\tab Origination Host Name: \cf5\b {2}\cf4\par.
        /// </summary>
        internal static string MESSAGE_HEADER_FORMAT {
            get {
                return ResourceManager.GetString("MESSAGE_HEADER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \tab\tab New State: \cf5\b {0}\cf0\b0\par.
        /// </summary>
        internal static string NEW_STATE_FORMAT {
            get {
                return ResourceManager.GetString("NEW_STATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \fs22\tab\cf4 Feature\par
        ///\cf6\tab\tab No Results Returned.
        /// </summary>
        internal static string NO_RESULTS {
            get {
                return ResourceManager.GetString("NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \cf2\fs24 Request\cf3\par.
        /// </summary>
        internal static string REQUEST_SECTION {
            get {
                return ResourceManager.GetString("REQUEST_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \cf2 Response\cf3\par.
        /// </summary>
        internal static string RESPONSE_SECTION {
            get {
                return ResourceManager.GetString("RESPONSE_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string RTF_CLOSE {
            get {
                return ResourceManager.GetString("RTF_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \viewkind4\uc1\pard\sa200\sl276\slmult1\cf1\lang9\b\f0\fs32 {0} Results\par.
        /// </summary>
        internal static string RTF_HEADER_FORMAT {
            get {
                return ResourceManager.GetString("RTF_HEADER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green176\blue80;\red0\green128\blue64;\red79\green129\blue189;\red155\green187\blue89;\red247\green150\blue70;\red255\green0\blue0;}{\*\generator Feature Store Smoke Tester;}.
        /// </summary>
        internal static string RTF_PREAMBLE {
            get {
                return ResourceManager.GetString("RTF_PREAMBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \par\cf1\b0\fs24 {0}.
        /// </summary>
        internal static string STACK_TRACE_FORMAT {
            get {
                return ResourceManager.GetString("STACK_TRACE_FORMAT", resourceCulture);
            }
        }
    }
}
