//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ciroque.Foundations.FeatureStore.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ciroque.Foundations.FeatureStore.Core.ExceptionMessageResources", typeof(ExceptionMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred querying the data store for the Feature. The query parameters were: Id {0} and Space {1}. See the InnerException property for further details..
        /// </summary>
        internal static string CHECK_FEATURE_STATE_EXCEPTION {
            get {
                return ResourceManager.GetString("CHECK_FEATURE_STATE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Feature could not be created due to a duplicate key violation. The Id {0}, OwnerId {1}, and Space {2} already exist in the data store..
        /// </summary>
        internal static string DUPLICATE_KEY_VIOLATION {
            get {
                return ResourceManager.GetString("DUPLICATE_KEY_VIOLATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty Guid was specified for the OwnerId, this is not allowed. A non-empty OwnerId must be provided..
        /// </summary>
        internal static string EMPTY_OWNER_GUID_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("EMPTY_OWNER_GUID_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred creating the Feature. See the InnerException property for details..
        /// </summary>
        internal static string FEATURE_CREATION_EXCEPTION {
            get {
                return ResourceManager.GetString("FEATURE_CREATION_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Feature having Id {0} and Space {1} was found..
        /// </summary>
        internal static string FEATURE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FEATURE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred retrieving defined Features. The query parameters were: OwnerId {0} and Space {1}. See the InnerException property for further details..
        /// </summary>
        internal static string RETRIEVE_DEFINED_FEATURES_EXCEPTION {
            get {
                return ResourceManager.GetString("RETRIEVE_DEFINED_FEATURES_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred updating the Feature. The query parameters were: Id {0} and Space {1}. See the InnerException property for further details..
        /// </summary>
        internal static string UPDATE_FEATURE_STATE_EXCEPTION {
            get {
                return ResourceManager.GetString("UPDATE_FEATURE_STATE_EXCEPTION", resourceCulture);
            }
        }
    }
}
